// Amharic Translations for Work Progress Tracker

export const translations = {
  // Common
  common: {
    loading: 'በመጫን ላይ...',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    submit: 'አስገባ',
    edit: 'አርትዕ',
    delete: 'ሰርዝ',
    view: 'ይመልከቱ',
    back: 'ተመለስ',
    next: 'ቀጣይ',
    previous: 'ቀዳሚ',
    search: 'ፈልግ',
    filter: 'አጣራ',
    export: 'ወደ ውጭ ላክ',
    print: 'አትም',
    close: 'ዝጋ',
    yes: 'አዎ',
    no: 'አይ',
    ok: 'እሺ',
    error: 'ስህተት',
    success: 'ተሳክቷል',
    warning: 'ማስጠንቀቂያ',
    info: 'መረጃ',
    branch: 'ወረዳ',
    mainBranch: 'ክፍለ ከተማ',
    woreda: 'ወረዳ',
    subcity: 'ክፍለ ከተማ',
    goal: 'ግብ',
  },

  // Authentication
  auth: {
    login: 'ግባ',
    logout: 'ውጣ',
    username: 'የተጠቃሚ ስም',
    password: 'የይለፍ ቃል',
    loginTitle: 'ወደ የስራ እድገት መከታተያ ይግቡ',
    loginSubtitle: 'የወርሃዊ ሪፖርቶችዎን ለመከታተል እና ለማስገባት ይግቡ',
    enterUsername: 'የተጠቃሚ ስምዎን ያስገቡ',
    enterPassword: 'የይለፍ ቃልዎን ያስገቡ',
    loggingIn: 'በመግባት ላይ...',
    loginError: 'የመግቢያ ስህተት',
    invalidCredentials: 'ልክ ያልሆነ የተጠቃሚ ስም ወይም የይለፍ ቃል',
  },

  // Dashboard
  dashboard: {
    mainBranch: 'ክፍለ ከተማ ዳሽቦርድ',
    branch: 'ወረዳ ዳሽቦርድ',
    subcity: 'ክፍለ ከተማ ዳሽቦርድ',
    woreda: 'ወረዳ ዳሽቦርድ',
    welcome: 'እንኳን ደህና መጡ',
    overview: 'አጠቃላይ እይታ',
    statistics: 'ስታቲስቲክስ',
    recentActivity: 'የቅርብ ጊዜ እንቅስቃሴ',
    manageAnnualPlans: 'የዓመታዊ እቅዶችን ያስተዳድሩ እና በሁሉም ቅርንጫፎች ላይ እድገትን ይከታተሉ',
    submitAndTrack: 'የወርሃዊ ሪፖርቶችዎን ያስገቡ እና ይከታተሉ',
    showingUpcomingMonths: 'የሚመጡ ወራትን ብቻ በማሳየት ላይ',
  },

  // Annual Plan
  annualPlan: {
    title: 'የዓመታዊ እቅድ',
    createNew: 'አዲስ የዓመታዊ እቅድ ፍጠር',
    viewPlan: 'እቅድ ይመልከቱ',
    planTitle: 'የእቅድ ርዕስ',
    description: 'መግለጫ',
    year: 'ዓመት',
    targetNumber: 'እቅድ ቁጥር',
    targetAmount: 'እቅድ መጠን',
    targetUnits: 'እቅድ ክፍሎች',
    achievedAmount: 'የተሳካ መጠን',
    overallProgress: 'አጠቃላይ እድገት',
    monthlyTargets: 'ወርሃዊ እቅዶች',
    quarterlyProgress: 'ሩብ ዓመታዊ እድገት',
    monthlyBreakdown: 'ወርሃዊ ክፍፍል',
    noPlansYet: 'እስካሁን ምንም የዓመታዊ እቅዶች የሉም',
    createFirstPlan: 'የመጀመሪያውን እቅድዎን ይፍጠሩ',
    getStarted: 'የመጀመሪያውን የዓመታዊ እቅድዎን በመፍጠር ይጀምሩ። ስርዓቱ በራስ-ሰር ወደ 12 ወራት ይከፍለዋል።',
    autoGenerate: 'ምን ይከሰታል?',
    autoGenerateDesc: '12 ወርሃዊ ጊዜዎች በራስ-ሰር ይፈጠራሉ',
    evenlyDistributed: 'ወርሃዊ እቅዶች በእኩል ይከፋፈላሉ',
    reportsCreated: 'ለሁሉም 10 የቅርንጫፍ ተጠቃሚዎች ሪፖርቶች ይፈጠራሉ',
    deadlinesSet: 'የመጨረሻ ቀናት በእያንዳንዱ ወር መጨረሻ ላይ ይቀመጣሉ',
    enterTargetNumber: 'ለመከታተል የእቅድ ቁጥር ያስገቡ (ለምሳሌ የሰዎች ብዛት)',
    planTitlePlaceholder: 'ለምሳሌ፣ 2025 የሽያጭ እቅድ',
    descriptionPlaceholder: 'የዓመታዊ እቅድ አላማዎችን ይግለጹ...',
    targetNumberPlaceholder: 'ለምሳሌ፣ 1000 (የሰዎች ብዛት)',
    creatingPlan: 'እቅድ በመፍጠር ላይ...',
    createPlan: 'የዓመታዊ እቅድ ፍጠር',
    planCreated: 'የዓመታዊ እቅድ በተሳካ ሁኔታ ተፈጥሯል',
    failedToCreate: 'የዓመታዊ እቅድ መፍጠር አልተሳካም',
  },

  // Reports
  reports: {
    title: 'ሪፖርቶች',
    monthlyReports: 'ወርሃዊ ሪፖርቶች',
    submitReport: 'ሪፖርት አስገባ',
    viewReport: 'ሪፖርት ይመልከቱ',
    editReport: 'ሪፖርት አርትዕ',
    totalReports: 'ጠቅላላ ሪፖርቶች',
    pending: 'በመጠባበቅ ላይ',
    submitted: 'ገብቷል',
    late: 'ዘግይቷል',
    plan: 'እቅድ',
    period: 'ጊዜ',
    target: 'እቅድ',
    achieved: 'የተሳካ',
    progress: 'እድገት',
    deadline: 'የመጨረሻ ቀን',
    status: 'ሁኔታ',
    action: 'ተግባር',
    noReportsAvailable: 'ምንም ሪፖርቶች የሉም',
    reportsWillAppear: 'ሪፖርቶች የሚታዩት የዓመታዊ እቅዶች በዋና ቅርንጫፍ ከተፈጠሩ በኋላ ነው',
    loadingReports: 'ሪፖርቶች በመጫን ላይ...',
    viewEdit: 'ይመልከቱ/አርትዕ',
    achievedAmount: 'የተሳካ መጠን',
    achievedUnits: 'የተሳካ ክፍሎች',
    notes: 'ማስታወሻዎች',
    enterAchievedAmount: 'የተሳካውን መጠን ያስገቡ',
    enterAchievedUnits: 'የተሳካውን ክፍሎች ያስገቡ',
    addNotes: 'ማስታወሻዎች ያክሉ (አማራጭ)',
    submittingReport: 'ሪፖርት በማስገባት ላይ...',
    reportSubmitted: 'ሪፖርት በተሳካ ሁኔታ ገብቷል',
    failedToSubmit: 'ሪፖርት ማስገባት አልተሳካም',
  },

  // Actions
  actions: {
    title: 'ተግባራት',
    createActions: 'ተግባራት ፍጠር',
    actionReports: 'የተግባር ሪፖርቶች',
    submitActionReport: 'የተግባር ሪፖርት አስገባ',
    actionName: 'የተግባር ስም',
    planNumber: 'የእቅድ ቁጥር',
    targetActivity: 'እቅድ እንቅስቃሴ',
    actualActivity: 'ትክክለኛ እንቅስቃሴ',
    implementation: 'ትግበራ',
    month: 'ወር',
    noActionsYet: 'እስካሁን ምንም ተግባራት የሉም',
    createFirstAction: 'የመጀመሪያውን ተግባርዎን ይፍጠሩ',
    actionsWillAppear: 'ተግባራት የሚታዩት በዋና ቅርንጫፍ ከተፈጠሩ በኋላ ነው',
  },

  // Comparison
  comparison: {
    title: 'የቅርንጫፍ ንጽጽር',
    branchComparison: 'የቅርንጫፍ ንጽጽር',
    comparePerformance: 'በሁሉም ቅርንጫፎች መካከል አፈጻጸምን ያወዳድሩ',
    branch: 'ቅርንጫፍ',
    performance: 'አፈጻጸም',
    ranking: 'ደረጃ',
    topPerformers: 'ከፍተኛ አፈጻጸም ያላቸው',
    needsImprovement: 'መሻሻል ያስፈልጋል',
  },

  // Navigation
  nav: {
    dashboard: 'ዳሽቦርድ',
    createPlan: 'እቅድ ፍጠር',
    viewPlans: 'እቅዶችን ይመልከቱ',
    reports: 'ሪፖርቶች',
    actions: 'ተግባራት',
    comparison: 'ንጽጽር',
    settings: 'ቅንብሮች',
    profile: 'መገለጫ',
    help: 'እገዛ',
    logout: 'ውጣ',
  },

  // Administrative Terms
  admin: {
    subcity: 'ክፍለ ከተማ',
    woreda: 'ወረዳ',
    subcityDashboard: 'ክፍለ ከተማ ዳሽቦርድ',
    woredaDashboard: 'ወረዳ ዳሽቦርድ',
    subcityUser: 'ክፍለ ከተማ ተጠቃሚ',
    woredaUser: 'ወረዳ ተጠቃሚ',
    woredaUsers: 'የወረዳ ተጠቃሚዎች',
  },

  // Amharic Plans
  amharicPlans: {
    overview: 'የአማርኛ እቅዶች አጠቃላይ እይታ',
    totalPlans: 'ጠቅላላ እቅዶች',
    totalActivities: 'ጠቅላላ እንቅስቃሴዎች',
    participatingWoredas: 'ተሳታፊ ወረዳዎች',
    submittedReports: 'የተላኩ ሪፖርቶች',
    amharicPlanReports: 'የአማርኛ እቅድ ሪፖርቶች',
    woredaAmharicReports: 'የወረዳዎች የአማርኛ እቅድ ሪፖርቶች',
    noAmharicReports: 'የአማርኛ እቅድ ሪፖርቶች የሉም',
    noAmharicReportsFound: 'የአማርኛ እቅድ ሪፖርቶች አልተገኙም',
    manageAmharicPlans: 'የአማርኛ እቅዶችን ያስተዳድሩ እና በሁሉም ወረዳዎች ላይ እድገትን ይከታተሉ',
    performanceSummaryWaiting: 'የአፈጻጸም ማጠቃለያ ለማየት ወረዳዎች ሪፖርት ማስገባት አለባቸው',
    chartsWillAppear: 'ወረዳዎች የአማርኛ እቅድ ሪፖርቶችን ካስገቡ በኋላ እዚህ ይታያል',
  },

  // Months (Ethiopian Government Fiscal Year)
  months: {
    1: 'ሐምሌ',
    2: 'ነሐሴ',
    3: 'መስከረም',
    4: 'ጥቅምት',
    5: 'ኅዳር',
    6: 'ታኅሣሥ',
    7: 'ጥር',
    8: 'የካቲት',
    9: 'መጋቢት',
    10: 'ሚያዝያ',
    11: 'ግንቦት',
    12: 'ሰኔ',
  },

  // Status
  status: {
    pending: 'በመጠባበቅ ላይ',
    submitted: 'ገብቷል',
    approved: 'ጸድቋል',
    rejected: 'ውድቅ ሆኗል',
    late: 'ዘግይቷል',
    completed: 'ተጠናቋል',
    inProgress: 'በሂደት ላይ',
    notStarted: 'አልተጀመረም',
  },

  // Messages
  messages: {
    noData: 'ምንም መረጃ የለም',
    noResults: 'ምንም ውጤቶች አልተገኙም',
    loadingData: 'መረጃ በመጫን ላይ...',
    savingChanges: 'ለውጦች በመቀመጥ ላይ...',
    changesSaved: 'ለውጦች ተቀምጠዋል',
    errorOccurred: 'ስህተት ተከስቷል',
    tryAgain: 'እባክዎ እንደገና ይሞክሩ',
    confirmDelete: 'መሰረዝዎን እርግጠኛ ነዎት?',
    cannotUndo: 'ይህንን ተግባር መመለስ አይችሉም',
    deleteSuccess: 'በተሳካ ሁኔታ ተሰርዟል',
    deleteFailed: 'መሰረዝ አልተሳካም',
  },

  // Validation
  validation: {
    required: 'ይህ መስክ ያስፈልጋል',
    invalidEmail: 'ልክ ያልሆነ ኢሜይል አድራሻ',
    invalidNumber: 'ልክ ያልሆነ ቁጥር',
    minLength: 'ቢያንስ {min} ቁምፊዎች ያስፈልጋሉ',
    maxLength: 'ከፍተኛው {max} ቁምፊዎች ተፈቅደዋል',
    mustBePositive: 'ቁጥሩ አዎንታዊ መሆን አለበት',
    mustBeGreaterThan: 'ቁጥሩ ከ {value} የበለጠ መሆን አለበት',
  },

  // Additional translations for pages
  pages: {
    // ViewAnnualPlan
    backToDashboard: 'ወደ ዳሽቦርድ ተመለስ',
    createActions: 'ተግባራት ፍጠር',
    planNotFound: 'እቅድ አልተገኘም',
    monthlyTargets: 'ወርሃዊ እቅዶች',
    quarterlyProgress: 'ሩብ ዓመታዊ እድገት',
    monthlyBreakdown: 'ወርሃዊ ክፍፍል',
    
    // SubmitReport
    monthlyReport: 'ወርሃዊ ሪፖርት',
    targetAmount: 'እቅድ መጠን',
    targetUnits: 'እቅድ ክፍሎች',
    onTime: 'በጊዜው',
    overdue: 'ዘግይቷል',
    previouslySubmitted: 'ቀደም ብሎ ገብቷል በ',
    
    // ActionReports
    totalActions: 'ጠቅላላ ተግባራት',
    noActionReportsAvailable: 'ምንም የተግባር ሪፖርቶች የሉም',
    actionReportsWillAppear: 'የተግባር ሪፖርቶች የሚታዩት በዋና ቅርንጫፍ ተግባራት ከተፈጠሩ በኋላ ነው',
    loadingActionReports: 'የተግባር ሪፖርቶች በመጫን ላይ...',
    planActivity: 'የእቅድ እንቅስቃሴ',
    actual: 'ትክክለኛ',
    
    // CreateActions
    backToPlan: 'ወደ እቅድ ተመለስ',
    defineActions: 'ተግባራትን በእቅድ ቁጥሮች እና ተግባራት ይግለጹ። ቅርንጫፎች የተጠናቀቁ ትክክለኛ እንቅስቃሴዎችን ሪፖርት ያደርጋሉ።',
    actionTitle: 'የተግባር ርዕስ',
    addAnotherAction: 'ሌላ ተግባር ያክሉ',
    howItWorks: 'እንዴት ይሰራል',
    branchesWillSee: 'ቅርንጫፎች እነዚህን ተግባራት በወርሃዊ ሪፖርቶቻቸው ውስጥ ያያሉ',
    theyInputActual: 'የተጠናቀቁ ትክክለኛ እንቅስቃሴዎችን ያስገባሉ',
    systemCalculates: 'ስርዓቱ በራስ-ሰር ያሰላል: (ትክክለኛ / እቅድ) × 100%',
    youCanView: 'ሁሉንም ማስገባቶች ማየት እና እድገትን መከታተል ይችላሉ',
    creating: 'በመፍጠር ላይ...',
    
    // SubmitActionReport
    backToActionReports: 'ወደ የተግባር ሪፖርቶች ተመለስ',
    actionReport: 'የተግባር ሪፖርት',
    actualActivityCompleted: 'የተጠናቀቀ ትክክለኛ እንቅስቃሴ',
    enterActualActivity: 'የተጠናቀቀውን ትክክለኛ እንቅስቃሴ ያስገቡ',
    implementationPercentage: 'የትግበራ መቶኛ',
    calculation: 'ስሌት',
    
    // BranchComparison
    branchPerformanceComparison: 'የቅርንጫፍ አፈጻጸም ንጽጽር',
    compareProgress: 'በሁሉም ቅርንጫፎች መካከል እድገትን ያወዳድሩ',
    topPerformer: 'ከፍተኛ አፈጻጸም ያለው',
    averageProgress: 'አማካይ እድገት',
    progressComparison: 'የእድገት ንጽጽር',
    detailedBranchStatistics: 'ዝርዝር የቅርንጫፍ ስታቲስቲክስ',
    rank: 'ደረጃ',
    totalReports: 'ጠቅላላ ሪፖርቶች',
    totalAchieved: 'ጠቅላላ የተሳካ',
    avgProgress: 'አማካይ እድገት',
    trend: 'አዝማሚያ',
  },
};

// Helper function to get translation
export const t = (key) => {
  const keys = key.split('.');
  let value = translations;
  
  for (const k of keys) {
    value = value[k];
    if (!value) return key;
  }
  
  return value;
};

// Helper function to get month name
export const getMonthName = (monthNumber) => {
  return translations.months[monthNumber] || monthNumber;
};

// Helper function to get status text
export const getStatusText = (status) => {
  return translations.status[status] || status;
};


// Additional translations for summary and export features
export const summaryTranslations = {
  'የአፈጻጸም ማጠቃለያ': 'Performance Summary',
  'ሪፖርት አውርድ': 'Export Report',
  'PDF ውጣ': 'Export as PDF',
  'Excel ውጣ': 'Export as Excel',
  'Word ውጣ': 'Export as Word',
  'የቅርንጫፍ እድገት ንፅፅር': 'Branch Progress Comparison',
  'የደረጃ ስርጭት': 'Grade Distribution',
  'የቅርንጫፍ ደረጃዎች': 'Branch Grades',
  'ምርጥ አፈጻጸም ያላቸው': 'Top Performers',
  'ደረጃ': 'Grade',
  'እድገት %': 'Progress %',
  'ቅርንጫፎች ተመርጠዋል': 'branches selected',
  'ሁሉንም አትመርጥ': 'Deselect All',
  'ሁሉንም ምረጥ': 'Select All',
  'ምንም ሪፖርቶች የሉም': 'No reports to export',
  'እጅግ በጣም ጥሩ': 'Outstanding',
  'በጣም ጥሩ': 'Excellent',
  'ጥሩ': 'Good',
  'ከመካከለኛ በላይ': 'Above Average',
  'መካከለኛ': 'Average',
  'ከመካከለኛ በታች': 'Below Average',
  'መሻሻል ያስፈልጋል': 'Needs Improvement'
};


// Deadline and date translations
export const deadlineTranslations = {
  'ቀናት ቀርተዋል': 'days left',
  'ጊዜው አልፏል': 'Deadline passed',
  'ቀናት': 'days',
  'Passed': 'Passed'
};
