// Amharic Translations for Work Progress Tracker

export const translations = {
  // Common
  common: {
    loading: 'በመጫን ላይ...',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    submit: 'አስገባ',
    edit: 'አርትዕ',
    delete: 'ሰርዝ',
    view: 'ይመልከቱ',
    back: 'ተመለስ',
    next: 'ቀጣይ',
    previous: 'ቀዳሚ',
    search: 'ፈልግ',
    filter: 'አጣራ',
    export: 'ወደ ውጭ ላክ',
    print: 'አትም',
    close: 'ዝጋ',
    yes: 'አዎ',
    no: 'አይ',
    ok: 'እሺ',
    error: 'ስህተት',
    success: 'ተሳክቷል',
    warning: 'ማስጠንቀቂያ',
    info: 'መረጃ',
  },

  // Authentication
  auth: {
    login: 'ግባ',
    logout: 'ውጣ',
    username: 'የተጠቃሚ ስም',
    password: 'የይለፍ ቃል',
    loginTitle: 'ወደ የስራ እድገት መከታተያ ይግቡ',
    loginSubtitle: 'የወርሃዊ ሪፖርቶችዎን ለመከታተል እና ለማስገባት ይግቡ',
    enterUsername: 'የተጠቃሚ ስምዎን ያስገቡ',
    enterPassword: 'የይለፍ ቃልዎን ያስገቡ',
    loggingIn: 'በመግባት ላይ...',
    loginError: 'የመግቢያ ስህተት',
    invalidCredentials: 'ልክ ያልሆነ የተጠቃሚ ስም ወይም የይለፍ ቃል',
  },

  // Dashboard
  dashboard: {
    mainBranch: 'ዋና ቅርንጫፍ ዳሽቦርድ',
    branch: 'ቅርንጫፍ ዳሽቦርድ',
    welcome: 'እንኳን ደህና መጡ',
    overview: 'አጠቃላይ እይታ',
    statistics: 'ስታቲስቲክስ',
    recentActivity: 'የቅርብ ጊዜ እንቅስቃሴ',
    manageAnnualPlans: 'የዓመታዊ እቅዶችን ያስተዳድሩ እና በሁሉም ቅርንጫፎች ላይ እድገትን ይከታተሉ',
    submitAndTrack: 'የወርሃዊ ሪፖርቶችዎን ያስገቡ እና ይከታተሉ',
    showingUpcomingMonths: 'የሚመጡ ወራትን ብቻ በማሳየት ላይ',
  },

  // Annual Plan
  annualPlan: {
    title: 'የዓመታዊ እቅድ',
    createNew: 'አዲስ የዓመታዊ እቅድ ፍጠር',
    viewPlan: 'እቅድ ይመልከቱ',
    planTitle: 'የእቅድ ርዕስ',
    description: 'መግለጫ',
    year: 'ዓመት',
    targetNumber: 'ዒላማ ቁጥር',
    targetAmount: 'ዒላማ መጠን',
    targetUnits: 'ዒላማ ክፍሎች',
    achievedAmount: 'የተሳካ መጠን',
    overallProgress: 'አጠቃላይ እድገት',
    monthlyTargets: 'ወርሃዊ ዒላማዎች',
    quarterlyProgress: 'ሩብ ዓመታዊ እድገት',
    monthlyBreakdown: 'ወርሃዊ ክፍፍል',
    noPlansYet: 'እስካሁን ምንም የዓመታዊ እቅዶች የሉም',
    createFirstPlan: 'የመጀመሪያውን እቅድዎን ይፍጠሩ',
    getStarted: 'የመጀመሪያውን የዓመታዊ እቅድዎን በመፍጠር ይጀምሩ። ስርዓቱ በራስ-ሰር ወደ 12 ወራት ይከፍለዋል።',
    autoGenerate: 'ምን ይከሰታል?',
    autoGenerateDesc: '12 ወርሃዊ ጊዜዎች በራስ-ሰር ይፈጠራሉ',
    evenlyDistributed: 'ወርሃዊ ዒላማዎች በእኩል ይከፋፈላሉ',
    reportsCreated: 'ለሁሉም 10 የቅርንጫፍ ተጠቃሚዎች ሪፖርቶች ይፈጠራሉ',
    deadlinesSet: 'የመጨረሻ ቀናት በእያንዳንዱ ወር መጨረሻ ላይ ይቀመጣሉ',
    enterTargetNumber: 'ለመከታተል የዒላማ ቁጥር ያስገቡ (ለምሳሌ የሰዎች ብዛት)',
    planTitlePlaceholder: 'ለምሳሌ፣ 2025 የሽያጭ ዒላማ',
    descriptionPlaceholder: 'የዓመታዊ እቅድ አላማዎችን ይግለጹ...',
    targetNumberPlaceholder: 'ለምሳሌ፣ 1000 (የሰዎች ብዛት)',
    creatingPlan: 'እቅድ በመፍጠር ላይ...',
    createPlan: 'የዓመታዊ እቅድ ፍጠር',
    planCreated: 'የዓመታዊ እቅድ በተሳካ ሁኔታ ተፈጥሯል',
    failedToCreate: 'የዓመታዊ እቅድ መፍጠር አልተሳካም',
  },

  // Reports
  reports: {
    title: 'ሪፖርቶች',
    monthlyReports: 'ወርሃዊ ሪፖርቶች',
    submitReport: 'ሪፖርት አስገባ',
    viewReport: 'ሪፖርት ይመልከቱ',
    editReport: 'ሪፖርት አርትዕ',
    totalReports: 'ጠቅላላ ሪፖርቶች',
    pending: 'በመጠባበቅ ላይ',
    submitted: 'ገብቷል',
    late: 'ዘግይቷል',
    plan: 'እቅድ',
    period: 'ጊዜ',
    target: 'ዒላማ',
    achieved: 'የተሳካ',
    progress: 'እድገት',
    deadline: 'የመጨረሻ ቀን',
    status: 'ሁኔታ',
    action: 'ተግባር',
    noReportsAvailable: 'ምንም ሪፖርቶች የሉም',
    reportsWillAppear: 'ሪፖርቶች የሚታዩት የዓመታዊ እቅዶች በዋና ቅርንጫፍ ከተፈጠሩ በኋላ ነው',
    loadingReports: 'ሪፖርቶች በመጫን ላይ...',
    viewEdit: 'ይመልከቱ/አርትዕ',
    achievedAmount: 'የተሳካ መጠን',
    achievedUnits: 'የተሳካ ክፍሎች',
    notes: 'ማስታወሻዎች',
    enterAchievedAmount: 'የተሳካውን መጠን ያስገቡ',
    enterAchievedUnits: 'የተሳካውን ክፍሎች ያስገቡ',
    addNotes: 'ማስታወሻዎች ያክሉ (አማራጭ)',
    submittingReport: 'ሪፖርት በማስገባት ላይ...',
    reportSubmitted: 'ሪፖርት በተሳካ ሁኔታ ገብቷል',
    failedToSubmit: 'ሪፖርት ማስገባት አልተሳካም',
  },

  // Actions
  actions: {
    title: 'ተግባራት',
    createActions: 'ተግባራት ፍጠር',
    actionReports: 'የተግባር ሪፖርቶች',
    submitActionReport: 'የተግባር ሪፖርት አስገባ',
    actionName: 'የተግባር ስም',
    planNumber: 'የእቅድ ቁጥር',
    targetActivity: 'ዒላማ እንቅስቃሴ',
    actualActivity: 'ትክክለኛ እንቅስቃሴ',
    implementation: 'ትግበራ',
    month: 'ወር',
    noActionsYet: 'እስካሁን ምንም ተግባራት የሉም',
    createFirstAction: 'የመጀመሪያውን ተግባርዎን ይፍጠሩ',
    actionsWillAppear: 'ተግባራት የሚታዩት በዋና ቅርንጫፍ ከተፈጠሩ በኋላ ነው',
  },

  // Comparison
  comparison: {
    title: 'የቅርንጫፍ ንጽጽር',
    branchComparison: 'የቅርንጫፍ ንጽጽር',
    comparePerformance: 'በሁሉም ቅርንጫፎች መካከል አፈጻጸምን ያወዳድሩ',
    branch: 'ቅርንጫፍ',
    performance: 'አፈጻጸም',
    ranking: 'ደረጃ',
    topPerformers: 'ከፍተኛ አፈጻጸም ያላቸው',
    needsImprovement: 'መሻሻል ያስፈልጋል',
  },

  // Navigation
  nav: {
    dashboard: 'ዳሽቦርድ',
    createPlan: 'እቅድ ፍጠር',
    viewPlans: 'እቅዶችን ይመልከቱ',
    reports: 'ሪፖርቶች',
    actions: 'ተግባራት',
    comparison: 'ንጽጽር',
    settings: 'ቅንብሮች',
    profile: 'መገለጫ',
    help: 'እገዛ',
    logout: 'ውጣ',
  },

  // Months (Ethiopian Government Fiscal Year)
  months: {
    1: 'ሐምሌ',
    2: 'ነሐሴ',
    3: 'መስከረም',
    4: 'ጥቅምት',
    5: 'ኅዳር',
    6: 'ታኅሣሥ',
    7: 'ጥር',
    8: 'የካቲት',
    9: 'መጋቢት',
    10: 'ሚያዝያ',
    11: 'ግንቦት',
    12: 'ሰኔ',
  },

  // Status
  status: {
    pending: 'በመጠባበቅ ላይ',
    submitted: 'ገብቷል',
    approved: 'ጸድቋል',
    rejected: 'ውድቅ ሆኗል',
    late: 'ዘግይቷል',
    completed: 'ተጠናቋል',
    inProgress: 'በሂደት ላይ',
    notStarted: 'አልተጀመረም',
  },

  // Messages
  messages: {
    noData: 'ምንም መረጃ የለም',
    noResults: 'ምንም ውጤቶች አልተገኙም',
    loadingData: 'መረጃ በመጫን ላይ...',
    savingChanges: 'ለውጦች በመቀመጥ ላይ...',
    changesSaved: 'ለውጦች ተቀምጠዋል',
    errorOccurred: 'ስህተት ተከስቷል',
    tryAgain: 'እባክዎ እንደገና ይሞክሩ',
    confirmDelete: 'መሰረዝዎን እርግጠኛ ነዎት?',
    cannotUndo: 'ይህንን ተግባር መመለስ አይችሉም',
    deleteSuccess: 'በተሳካ ሁኔታ ተሰርዟል',
    deleteFailed: 'መሰረዝ አልተሳካም',
  },

  // Validation
  validation: {
    required: 'ይህ መስክ ያስፈልጋል',
    invalidEmail: 'ልክ ያልሆነ ኢሜይል አድራሻ',
    invalidNumber: 'ልክ ያልሆነ ቁጥር',
    minLength: 'ቢያንስ {min} ቁምፊዎች ያስፈልጋሉ',
    maxLength: 'ከፍተኛው {max} ቁምፊዎች ተፈቅደዋል',
    mustBePositive: 'ቁጥሩ አዎንታዊ መሆን አለበት',
    mustBeGreaterThan: 'ቁጥሩ ከ {value} የበለጠ መሆን አለበት',
  },
};

// Helper function to get translation
export const t = (key) => {
  const keys = key.split('.');
  let value = translations;
  
  for (const k of keys) {
    value = value[k];
    if (!value) return key;
  }
  
  return value;
};

// Helper function to get month name
export const getMonthName = (monthNumber) => {
  return translations.months[monthNumber] || monthNumber;
};

// Helper function to get status text
export const getStatusText = (status) => {
  return translations.status[status] || status;
};
